# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_session_base_pb2 as game__session__base__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_session_base_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameSessionBaseServiceStub(object):
    """Базовый сервис игровой сессии.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/game_session_base.GameSessionBaseService/Connect',
                request_serializer=game__session__base__pb2.ConnectRequest.SerializeToString,
                response_deserializer=game__session__base__pb2.ConnectReply.FromString,
                _registered_method=True)
        self.PlaySession = channel.stream_stream(
                '/game_session_base.GameSessionBaseService/PlaySession',
                request_serializer=game__session__base__pb2.StrategyReaction.SerializeToString,
                response_deserializer=game__session__base__pb2.GameFieldState.FromString,
                _registered_method=True)


class GameSessionBaseServiceServicer(object):
    """Базовый сервис игровой сессии.
    """

    def Connect(self, request, context):
        """Подключение к игровой сессии.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaySession(self, request_iterator, context):
        """Подключение к игровой сессии.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameSessionBaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=game__session__base__pb2.ConnectRequest.FromString,
                    response_serializer=game__session__base__pb2.ConnectReply.SerializeToString,
            ),
            'PlaySession': grpc.stream_stream_rpc_method_handler(
                    servicer.PlaySession,
                    request_deserializer=game__session__base__pb2.StrategyReaction.FromString,
                    response_serializer=game__session__base__pb2.GameFieldState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game_session_base.GameSessionBaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('game_session_base.GameSessionBaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameSessionBaseService(object):
    """Базовый сервис игровой сессии.
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/game_session_base.GameSessionBaseService/Connect',
            game__session__base__pb2.ConnectRequest.SerializeToString,
            game__session__base__pb2.ConnectReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaySession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/game_session_base.GameSessionBaseService/PlaySession',
            game__session__base__pb2.StrategyReaction.SerializeToString,
            game__session__base__pb2.GameFieldState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
